
AudioPlayArrayResmp sound0;
AudioPlayArrayResmp sound1;
AudioPlayArrayResmp sound2;
AudioPlayArrayResmp sound3;
AudioPlayArrayResmp sound4;
AudioPlayArrayResmp sound5;
AudioPlayArrayResmp sound6;
AudioPlayArrayResmp sound7;
AudioPlayArrayResmp sound8;
AudioPlayArrayResmp sound9;
AudioPlayArrayResmp sound10;
AudioPlayArrayResmp sound11;
AudioPlayArrayResmp sound12;
/* INIT AUTOGENERATED */


#include <Audio.h>
#include <Wire.h>
#include <SPI.h>
#include <SD.h>
#include <SerialFlash.h>

// GUItool: begin automatically generated code
AudioSynthNoisePink      pink1;          //xy=66,957
AudioSynthWaveform       waveform13_1;      //xy=67,1015
AudioSynthWaveform       waveform13_2;      //xy=68,1053
AudioSynthWaveform       waveform11_1;      //xy=75.5,766
AudioSynthWaveform       waveform11_2;      //xy=75.5,812
AudioSynthWaveform       waveform12_1;      //xy=76,861
AudioSynthWaveform       waveform12_2;      //xy=76,899
AudioSynthWaveform       waveform14_1;      //xy=76,1156
AudioSynthWaveform       waveform14_2;      //xy=76,1191
AudioMixer4              mixer_waveform12;        //xy=298,935
AudioMixer4              mixer_waveform11;        //xy=300,849
AudioMixer4              mixer_waveform14;         //xy=307,1162
AudioMixer4              mixer_waveform13; //xy=311,1022
AudioMixer4              waveformmixer11;         //xy=500,854
AudioSynthKarplusStrong  string11;        //xy=504,889
AudioMixer4              waveformmixer12;         //xy=504,938
AudioSynthSimpleDrum     drum11;          //xy=510,796
AudioSynthKarplusStrong  string12;        //xy=512,968
AudioSynthKarplusStrong  string13;       //xy=512,1072
AudioSynthSimpleDrum     drum14;          //xy=513,1126
AudioMixer4              waveformmixer14;         //xy=513,1166
AudioSynthSimpleDrum     drum12;          //xy=515,921
AudioMixer4              waveformmixer13; //xy=515,1025
AudioSynthKarplusStrong  string1;        //xy=517,1235
AudioSynthSimpleDrum     drum13;         //xy=520,1003
AudioPlaySdRaw           playRaw0;       //xy=664,127
AudioEffectEnvelope      envelope2;      //xy=665,239
AudioEffectEnvelope      envelope3;      //xy=665,307
AudioEffectEnvelope      envelope1;      //xy=666,182
AudioEffectEnvelope      envelope4;      //xy=667,375
AudioEffectEnvelope      envelope0;      //xy=671,72
AudioEffectEnvelope      envelope8;      //xy=671,640
AudioEffectEnvelope      envelope5;      //xy=673,445
AudioEffectEnvelope      envelope6;      //xy=673,510
AudioEffectEnvelope      envelope11;     //xy=672,862
AudioEffectEnvelope      envelope9;      //xy=673,711
AudioEffectEnvelope      envelope7;      //xy=676,571
AudioEffectEnvelope      envelope10;     //xy=677,785
AudioEffectEnvelope      envelope14;     //xy=676,1105
AudioEffectEnvelope      envelope13;     //xy=677,1031
AudioEffectEnvelope      envelope12;     //xy=679,949
AudioAmplifier           amp0;           //xy=824,446
AudioAmplifier           amp5;           //xy=826,446
AudioAmplifier           amp1;           //xy=829,182
AudioAmplifier           amp4;           //xy=829,375
AudioAmplifier           amp6;           //xy=829,511
AudioAmplifier           amp2;           //xy=833,238
AudioAmplifier           amp3;           //xy=833,304
AudioAmplifier           amp7;           //xy=832,570
AudioAmplifier           amp14;          //xy=832,1104
AudioAmplifier           amp9;           //xy=834,714
AudioAmplifier           amp11;          //xy=834,864
AudioAmplifier           amp8;           //xy=837,638
AudioAmplifier           amp10;          //xy=839,786
AudioAmplifier           amp12;          //xy=841,949
AudioAmplifier           amp13;          //xy=843,1029
AudioEffectBitcrusher    bitcrusher11;    //xy=998,865
AudioEffectBitcrusher    bitcrusher12;    //xy=1010,947
AudioEffectBitcrusher    bitcrusher13;   //xy=1011,1030
AudioEffectBitcrusher    bitcrusher14;    //xy=1021,1106
AudioFilterStateVariable filter13;       //xy=1172,1036
AudioFilterStateVariable filter14;       //xy=1179,1113
AudioFilterStateVariable filter12;       //xy=1180,955
AudioFilterStateVariable filter11;       //xy=1182,868
AudioFilterStateVariable filter0;        //xy=1300,494
AudioFilterStateVariable filter5;        //xy=1300,494
AudioFilterStateVariable filter1;        //xy=1302,272
AudioFilterStateVariable filter2;        //xy=1303,329
AudioFilterStateVariable filter6;        //xy=1305,550
AudioFilterStateVariable filter7;        //xy=1305,604
AudioFilterStateVariable filter9;        //xy=1305,716
AudioFilterStateVariable filter3;        //xy=1307,391
AudioFilterStateVariable filter8;        //xy=1306,665
AudioFilterStateVariable filter4;        //xy=1307,441
AudioFilterStateVariable filter10;       //xy=1308,774
AudioMixer4              filtermixer13;  //xy=1341,1042
AudioMixer4              filtermixer11;        //xy=1344,872
AudioMixer4              filtermixer14;         //xy=1346,1119
AudioMixer4              filtermixer12;        //xy=1349,961
AudioEffectFreeverb      freeverb14;      //xy=1504,1152
AudioEffectFlange        flange14;        //xy=1514,1113
AudioEffectFreeverb      freeverb13;     //xy=1526,1060
AudioEffectFlange        flange11;        //xy=1528,861
AudioEffectFlange        flange13;       //xy=1530,1018
AudioEffectFlange        flange12;        //xy=1538,940
AudioEffectFreeverb      freeverb12;      //xy=1538,976
AudioEffectFreeverb      freeverb11;      //xy=1541,893
AudioMixer4              mixer0;         //xy=1620,96
AudioMixer4              mixer1;         //xy=1621,358
AudioMixer4              mixer2;         //xy=1625,567
AudioMixer4              mixer3;         //xy=1752,766
AudioMixer4              mixer5;        //xy=1846,935
AudioMixer4              mixer_end;      //xy=1958,678
AudioMixer4              mixer4;         //xy=2106,1064
AudioMixer4              mixerPlay;      //xy=2144,677
AudioInputI2S            i2s2;           //xy=2245,805
AudioOutputI2S           i2s1;           //xy=2433,682
AudioRecordQueue         queue1;         //xy=2441,804
AudioConnection          patchCord1(pink1, 0, mixer_waveform13, 2);
AudioConnection          patchCord2(pink1, 0, mixer_waveform14, 3);
AudioConnection          patchCord3(pink1, 0, mixer_waveform12, 2);
AudioConnection          patchCord4(pink1, 0, mixer_waveform11, 2);
AudioConnection          patchCord5(waveform13_1, 0, mixer_waveform13, 0);
AudioConnection          patchCord6(waveform13_2, 0, mixer_waveform13, 1);
AudioConnection          patchCord7(waveform11_1, 0, mixer_waveform11, 0);
AudioConnection          patchCord8(waveform11_2, 0, mixer_waveform11, 1);
AudioConnection          patchCord9(waveform12_1, 0, mixer_waveform12, 0);
AudioConnection          patchCord10(waveform12_2, 0, mixer_waveform12, 1);
AudioConnection          patchCord11(waveform14_1, 0, mixer_waveform14, 0);
AudioConnection          patchCord12(waveform14_2, 0, mixer_waveform14, 1);
AudioConnection          patchCord13(mixer_waveform12, 0, waveformmixer12, 1);
AudioConnection          patchCord14(mixer_waveform11, 0, waveformmixer11, 1);
AudioConnection          patchCord15(mixer_waveform14, 0, waveformmixer14, 1);
AudioConnection          patchCord16(mixer_waveform13, 0, waveformmixer13, 1);
AudioConnection          patchCord17(waveformmixer11, envelope11);
AudioConnection          patchCord18(string11, 0, waveformmixer11, 2);
AudioConnection          patchCord19(waveformmixer12, envelope12);
AudioConnection          patchCord20(drum11, 0, waveformmixer11, 0);
AudioConnection          patchCord21(string12, 0, waveformmixer12, 2);
AudioConnection          patchCord22(string13, 0, waveformmixer13, 2);
AudioConnection          patchCord23(drum14, 0, waveformmixer14, 0);
AudioConnection          patchCord24(waveformmixer14, envelope14);
AudioConnection          patchCord25(drum12, 0, waveformmixer12, 0);
AudioConnection          patchCord26(waveformmixer13, envelope13);
AudioConnection          patchCord27(string1, 0, waveformmixer14, 2);
AudioConnection          patchCord28(drum13, 0, waveformmixer13, 0);
AudioConnection          patchCord29(playRaw0, 0, mixer0, 1);
AudioConnection          patchCord30(playRaw0, 0, mixer0, 2);
AudioConnection          patchCord31(envelope2, amp2);
AudioConnection          patchCord32(envelope3, amp3);
AudioConnection          patchCord33(envelope1, amp1);
AudioConnection          patchCord34(envelope4, amp4);
AudioConnection          patchCord35(envelope0, 0, mixer0, 0);
AudioConnection          patchCord36(envelope8, amp8);
AudioConnection          patchCord37(envelope5, amp5);
AudioConnection          patchCord38(envelope6, amp6);
AudioConnection          patchCord39(envelope11, amp11);
AudioConnection          patchCord40(envelope9, amp9);
AudioConnection          patchCord41(envelope7, amp7);
AudioConnection          patchCord42(envelope10, amp10);
AudioConnection          patchCord43(envelope14, amp14);
AudioConnection          patchCord44(envelope13, amp13);
AudioConnection          patchCord45(envelope12, amp12);
AudioConnection          patchCord46(amp5, 0, filter5, 0);
AudioConnection          patchCord47(amp1, 0, filter1, 0);
AudioConnection          patchCord48(amp4, 0, filter4, 0);
AudioConnection          patchCord49(amp6, 0, filter6, 0);
AudioConnection          patchCord50(amp2, 0, filter2, 0);
AudioConnection          patchCord51(amp3, 0, filter3, 0);
AudioConnection          patchCord52(amp7, 0, filter7, 0);
AudioConnection          patchCord53(amp14, bitcrusher14);
AudioConnection          patchCord54(amp9, 0, filter9, 0);
AudioConnection          patchCord55(amp11, bitcrusher11);
AudioConnection          patchCord56(amp8, 0, filter8, 0);
AudioConnection          patchCord57(amp10, 0, filter10, 0);
AudioConnection          patchCord58(amp12, bitcrusher12);
AudioConnection          patchCord59(amp13, bitcrusher13);
AudioConnection          patchCord60(bitcrusher11, 0, filter11, 0);
AudioConnection          patchCord61(bitcrusher12, 0, filter12, 0);
AudioConnection          patchCord62(bitcrusher13, 0, filter13, 0);
AudioConnection          patchCord63(bitcrusher14, 0, filter14, 0);
AudioConnection          patchCord64(filter13, 0, filtermixer13, 0);
AudioConnection          patchCord65(filter13, 1, filtermixer13, 1);
AudioConnection          patchCord66(filter13, 2, filtermixer13, 2);
AudioConnection          patchCord67(filter14, 0, filtermixer14, 0);
AudioConnection          patchCord68(filter14, 1, filtermixer14, 1);
AudioConnection          patchCord69(filter14, 2, filtermixer14, 2);
AudioConnection          patchCord70(filter12, 0, filtermixer12, 0);
AudioConnection          patchCord71(filter12, 1, filtermixer12, 1);
AudioConnection          patchCord72(filter12, 2, filtermixer12, 2);
AudioConnection          patchCord73(filter11, 0, filtermixer11, 0);
AudioConnection          patchCord74(filter11, 1, filtermixer11, 1);
AudioConnection          patchCord75(filter11, 2, filtermixer11, 2);
AudioConnection          patchCord76(filter5, 0, mixer2, 0);
AudioConnection          patchCord77(filter1, 0, mixer1, 0);
AudioConnection          patchCord78(filter2, 0, mixer1, 1);
AudioConnection          patchCord79(filter6, 0, mixer2, 1);
AudioConnection          patchCord80(filter7, 0, mixer2, 2);
AudioConnection          patchCord81(filter9, 0, mixer3, 0);
AudioConnection          patchCord82(filter3, 0, mixer1, 2);
AudioConnection          patchCord83(filter8, 0, mixer2, 3);
AudioConnection          patchCord84(filter4, 0, mixer1, 3);
AudioConnection          patchCord85(filter10, 0, mixer3, 1);
AudioConnection          patchCord86(filtermixer13, flange13);
AudioConnection          patchCord87(filtermixer13, freeverb13);
AudioConnection          patchCord88(filtermixer11, flange11);
AudioConnection          patchCord89(filtermixer11, freeverb11);
AudioConnection          patchCord90(filtermixer14, flange14);
AudioConnection          patchCord91(filtermixer14, freeverb14);
AudioConnection          patchCord92(filtermixer12, flange12);
AudioConnection          patchCord93(filtermixer12, freeverb12);
AudioConnection          patchCord94(freeverb14, 0, mixer4, 3);
AudioConnection          patchCord95(flange14, 0, mixer4, 2);
AudioConnection          patchCord96(freeverb13, 0, mixer4, 1);
AudioConnection          patchCord97(flange11, 0, mixer5, 0);
AudioConnection          patchCord98(flange13, 0, mixer4, 0);
AudioConnection          patchCord99(flange12, 0, mixer5, 2);
AudioConnection          patchCord100(freeverb12, 0, mixer5, 3);
AudioConnection          patchCord101(freeverb11, 0, mixer5, 1);
AudioConnection          patchCord102(mixer0, 0, mixerPlay, 2);
AudioConnection          patchCord103(mixer1, 0, mixer_end, 0);
AudioConnection          patchCord104(mixer2, 0, mixer_end, 1);
AudioConnection          patchCord105(mixer3, 0, mixer_end, 2);
AudioConnection          patchCord106(mixer5, 0, mixer3, 2);
AudioConnection          patchCord107(mixer_end, 0, mixerPlay, 0);
AudioConnection          patchCord108(mixer_end, 0, mixerPlay, 1);
AudioConnection          patchCord109(mixer4, 0, mixer_end, 3);
AudioConnection          patchCord110(mixerPlay, 0, i2s1, 0);
AudioConnection          patchCord111(mixerPlay, 0, i2s1, 1);
AudioConnection          patchCord112(i2s2, 0, queue1, 0);
AudioControlSGTL5000     sgtl5000_1;     //xy=2257,852
// GUItool: end automatically generated code



// --- ADDITIONAL sound declarations below here ... ---//
// --- AudioPlayArrayResmp doesnt exist in GUItool ---//
AudioAnalyzePeak         peak1; 
AudioConnection          patchCord2121(playRaw0, 0, peak1, 0);
AudioConnection snd0(sound0, envelope0);
AudioConnection snd1(sound1, envelope1);
AudioConnection snd2(sound2, envelope2);
AudioConnection snd3(sound3, envelope3);
AudioConnection snd4(sound4, envelope4);
AudioConnection snd5(sound5, envelope5);
AudioConnection snd6(sound6, envelope6);
AudioConnection snd7(sound7, envelope7);
AudioConnection snd8(sound8, envelope8);
AudioConnection snd9(sound9, envelope9);
AudioConnection snd10(sound10, envelope10);
AudioConnection snd11(sound11, envelope11);
AudioConnection snd12(sound12, envelope12);