/** Laser-ready SVG serialization */

import { unfold } from "./unfold.js";
import { nestPanels } from "./nest.js";

export function buildCutModel(doc) {
  const { panels, error } = unfold(doc);
  if (error || !panels.length) {
    return { error: error || "No panels", nest: null, panels: [] };
  }
  const maxW = doc.fixedPanels?.length
    ? Math.max(400, ...panels.map((p) => (p.width || 0) + 16))
    : Math.max(280, doc.depth * 6);
  const nest = nestPanels(panels, { margin: 8, maxRowWidth: maxW });
  return { panels, nest, error: null };
}

export function exportSvg(doc, { labels = false } = {}) {
  const model = buildCutModel(doc);
  if (model.error || !model.nest) {
    throw new Error(model.error || "Nothing to export");
  }

  const { nest } = model;
  const w = nest.width;
  const h = nest.height;

  const parts = [];
  parts.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${fmt(w)}mm" height="${fmt(h)}mm" viewBox="0 0 ${fmt(w)} ${fmt(h)}">`
  );
  parts.push(`  <title>TŒRN case — laser cut</title>`);
  parts.push(`  <desc>Generated by TŒRN Case Generator. Units: mm. Stroke cut paths.</desc>`);

  for (const item of nest.items) {
    const { panel, x, y } = item;
    parts.push(`  <g id="${escapeAttr(panel.id)}" transform="translate(${fmt(x)} ${fmt(y)})">`);
    parts.push(
      `    <path class="cut" d="${escapeAttr(panel.outerPath)}" fill="none" stroke="#000000" stroke-width="0.1" />`
    );
    for (const hole of panel.holes) {
      parts.push(
        `    <path class="cut" d="${escapeAttr(hole.d)}" fill="none" stroke="#000000" stroke-width="0.1" />`
      );
    }
    if (labels) {
      parts.push(
        `    <text x="1" y="3" fill="#888888" stroke="none" font-size="2.5" font-family="sans-serif">${escapeXml(panel.label)}</text>`
      );
    }
    parts.push(`  </g>`);
  }

  parts.push(`</svg>`);
  return parts.join("\n");
}

function fmt(n) {
  return String(Math.round(n * 1000) / 1000);
}

function escapeAttr(s) {
  return String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

function escapeXml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
