/** Laser-ready SVG serialization */

import { unfold } from "./unfold.js";
import { nestPanels, packPrintsOnSheet } from "./nest.js";
import { TEXT_FONT_WEIGHT } from "./features.js";

function sheetOptsFromDoc(doc) {
  const s = doc.sheet || {};
  return {
    sheetWidth: Math.max(1, Number(s.width) || 600),
    sheetHeight: Math.max(1, Number(s.height) || 400),
    copies: Math.max(1, Math.floor(Number(s.copies) || 1)),
    border: Math.max(0, Number(s.border) || 0),
    gap: Math.max(0, Number(s.gap) ?? 8),
    layoutSeed: Math.max(0, Math.floor(Number(s.layoutSeed) || 0)),
  };
}

export function buildCutModel(doc) {
  const { panels, error } = unfold(doc);
  if (error || !panels.length) {
    return { error: error || "No panels", nest: null, pack: null, panels: [] };
  }

  const sheet = sheetOptsFromDoc(doc);
  const pack = packPrintsOnSheet(panels, sheet);

  const nest = pack.nest?.items?.length
    ? pack.nest
    : nestPanels(panels, {
        gap: sheet.gap,
        padding: 0,
        maxRowWidth: Math.max(280, sheet.sheetWidth - 2 * sheet.border),
      });

  return { panels, nest, pack, error: null, sheet };
}

export function exportSvg(doc, { labels = false } = {}) {
  const model = buildCutModel(doc);
  if (model.error || !model.nest) {
    throw new Error(model.error || "Nothing to export");
  }

  const pack = model.pack;
  if (pack && !pack.fits) {
    throw new Error(pack.message || "Does not fit on sheet");
  }

  if (pack?.flat && pack.nest?.items?.length) {
    return serializeFlatSvg(pack, { labels });
  }

  if (pack?.placements?.length) {
    return serializeTiledSvg(pack, { labels });
  }

  const { nest } = model;
  return serializeTiledSvg(
    {
      nest,
      sheetWidth: nest.width,
      sheetHeight: nest.height,
      placements: [{ x: 0, y: 0, rotate90: false, index: 0 }],
    },
    { labels }
  );
}

function serializeFlatSvg(pack, { labels }) {
  const w = pack.sheetWidth;
  const h = pack.sheetHeight;
  const parts = [];
  parts.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${fmt(w)}mm" height="${fmt(h)}mm" viewBox="0 0 ${fmt(w)} ${fmt(h)}">`
  );
  parts.push(`  <title>TŒRN case — laser cut</title>`);
  parts.push(
    `  <desc>Generated by TŒRN Case Generator. Units: mm. Outer face up. Sheet ${fmt(w)}×${fmt(h)} mm. Cuts = path.cut · Engraves = text.engrave</desc>`
  );
  parts.push(
    `  <style type="text/css"><![CDATA[
    .cut { fill: none; stroke: #000000; stroke-width: 0.1; }
    .engrave { fill: #000000; stroke: none; }
  ]]></style>`
  );

  for (const item of pack.nest.items) {
    const { panel, x, y } = item;
    const bx = item.bounds?.minX || 0;
    const by = item.bounds?.minY || 0;
    const id = escapeAttr(panel.id || "part");
    parts.push(`  <g id="${id}" transform="translate(${fmt(x - bx)} ${fmt(y - by)})">`);
    parts.push(
      `    <path class="cut" d="${escapeAttr(panel.outerPath)}" fill="none" stroke="#000000" stroke-width="0.1" />`
    );
    for (const hole of panel.holes || []) {
      parts.push(serializeHoleSvg(hole, "    "));
    }
    if (labels) {
      parts.push(
        `    <text x="${fmt(bx + 1)}" y="${fmt(by + 3)}" fill="#888888" stroke="none" font-size="2.5" font-family="sans-serif">${escapeXml(panel.label || panel.id)}</text>`
      );
    }
    parts.push(`  </g>`);
  }

  parts.push(`</svg>`);
  return parts.join("\n");
}

function serializeTiledSvg(pack, { labels }) {
  const nest = pack.nest;
  const svgW = pack.sheetWidth ?? nest.width;
  const svgH = pack.sheetHeight ?? nest.height;
  const nw = nest.width;
  const placements = pack.placements || [{ x: 0, y: 0, rotate90: false, index: 0 }];

  const parts = [];
  parts.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${fmt(svgW)}mm" height="${fmt(svgH)}mm" viewBox="0 0 ${fmt(svgW)} ${fmt(svgH)}">`
  );
  parts.push(`  <title>TŒRN case — laser cut</title>`);
  parts.push(
    `  <desc>Generated by TŒRN Case Generator. Units: mm. Outer face up. Sheet ${fmt(svgW)}×${fmt(svgH)} mm. Cuts = path.cut · Engraves = text.engrave</desc>`
  );
  parts.push(
    `  <style type="text/css"><![CDATA[
    .cut { fill: none; stroke: #000000; stroke-width: 0.1; }
    .engrave { fill: #000000; stroke: none; }
  ]]></style>`
  );

  for (const place of placements) {
    const gTransform = placeTransform(place, nw);
    const copyId = place.index != null ? `copy-${place.index}` : "copy-0";
    parts.push(`  <g id="${escapeAttr(copyId)}" transform="${escapeAttr(gTransform)}">`);
    for (const item of nest.items) {
      const { panel, x, y } = item;
      const bx = item.bounds?.minX || 0;
      const by = item.bounds?.minY || 0;
      parts.push(
        `    <g id="${escapeAttr(`${copyId}-${panel.id}`)}" transform="translate(${fmt(x - bx)} ${fmt(y - by)})">`
      );
      parts.push(
        `      <path class="cut" d="${escapeAttr(panel.outerPath)}" fill="none" stroke="#000000" stroke-width="0.1" />`
      );
      for (const hole of panel.holes || []) {
        parts.push(serializeHoleSvg(hole, "        "));
      }
      if (labels) {
        parts.push(
          `      <text x="${fmt(bx + 1)}" y="${fmt(by + 3)}" fill="#888888" stroke="none" font-size="2.5" font-family="sans-serif">${escapeXml(panel.label)}</text>`
        );
      }
      parts.push(`    </g>`);
    }
    parts.push(`  </g>`);
  }

  parts.push(`</svg>`);
  return parts.join("\n");
}

function placeTransform(place, nestW) {
  const ox = place.x || 0;
  const oy = place.y || 0;
  if (place.rotate90) {
    return `translate(${fmt(ox)} ${fmt(oy)}) translate(0 ${fmt(nestW)}) rotate(-90)`;
  }
  return `translate(${fmt(ox)} ${fmt(oy)})`;
}

/** Path cuts or Bebas Neue engraving text (filled — not a cut hole). */
function serializeHoleSvg(hole, indent = "    ") {
  if (hole?.type === "text") {
    const rot = Number(hole.rotation) || 0;
    const ls = Number(hole.letterSpacing) || 0;
    const size = Math.max(0.5, Number(hole.size) || 8);
    const x = Number(hole.x) || 0;
    const y = Number(hole.y) || 0;
    const transform = rot
      ? ` transform="rotate(${fmt(rot)} ${fmt(x)} ${fmt(y)})"`
      : "";
    // Filled engraving (laser raster/vector fill). Not a through-cut.
    return (
      `${indent}<text class="engrave"` +
      ` x="${fmt(x)}" y="${fmt(y)}"` +
      ` text-anchor="middle" dominant-baseline="central"` +
      ` font-family="Bebas Neue, BebasNeue, Impact, sans-serif"` +
      ` font-weight="${TEXT_FONT_WEIGHT}"` +
      ` font-size="${fmt(size)}"` +
      ` letter-spacing="${fmt(ls)}"` +
      ` fill="#000000" stroke="none"` +
      `${transform}>${escapeXml(hole.text || "")}</text>`
    );
  }
  if (hole?.d) {
    return `${indent}<path class="cut" d="${escapeAttr(hole.d)}" fill="none" stroke="#000000" stroke-width="0.1" />`;
  }
  return "";
}

function fmt(n) {
  return String(Math.round(n * 1000) / 1000);
}

function escapeAttr(s) {
  return String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

function escapeXml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
